//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reslang {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiabetesCarePlatform.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 異常值 的當地語系化字串。
        /// </summary>
        public static string AbnormalValue {
            get {
                return ResourceManager.GetString("AbnormalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 接受 的當地語系化字串。
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號 的當地語系化字串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號設定 的當地語系化字串。
        /// </summary>
        public static string AccountSetup {
            get {
                return ResourceManager.GetString("AccountSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 啟用 的當地語系化字串。
        /// </summary>
        public static string Acitve {
            get {
                return ResourceManager.GetString("Acitve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 晚期糖尿病眼疾 的當地語系化字串。
        /// </summary>
        public static string Advanceddiabeticeyedisease {
            get {
                return ResourceManager.GetString("Advanceddiabeticeyedisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 白蛋白Alb.(mg/dl) 的當地語系化字串。
        /// </summary>
        public static string Albumin {
            get {
                return ResourceManager.GetString("Albumin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 喝酒 的當地語系化字串。
        /// </summary>
        public static string Alcoholconsumption {
            get {
                return ResourceManager.GetString("Alcoholconsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 過敏史 的當地語系化字串。
        /// </summary>
        public static string Allergyhistory {
            get {
                return ResourceManager.GetString("Allergyhistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 截肢 的當地語系化字串。
        /// </summary>
        public static string Amputation {
            get {
                return ResourceManager.GetString("Amputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 心絞痛(Anginal chest pain) 的當地語系化字串。
        /// </summary>
        public static string Anginapectoris {
            get {
                return ResourceManager.GetString("Anginapectoris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 申請中 的當地語系化字串。
        /// </summary>
        public static string ApplyFor {
            get {
                return ResourceManager.GetString("ApplyFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 代理人指派 的當地語系化字串。
        /// </summary>
        public static string Assignagents {
            get {
                return ResourceManager.GetString("Assignagents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 時段指定 的當地語系化字串。
        /// </summary>
        public static string AssignTimes {
            get {
                return ResourceManager.GetString("AssignTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 審核 的當地語系化字串。
        /// </summary>
        public static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回到首頁 的當地語系化字串。
        /// </summary>
        public static string Back_to_Home_Page {
            get {
                return ResourceManager.GetString("Back_to_Home_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 長條圖 的當地語系化字串。
        /// </summary>
        public static string BarChart {
            get {
                return ResourceManager.GetString("BarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 基本資料 的當地語系化字串。
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 個人基本資料 的當地語系化字串。
        /// </summary>
        public static string Basicpersonalinformation {
            get {
                return ResourceManager.GetString("Basicpersonalinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 綁定 的當地語系化字串。
        /// </summary>
        public static string Binding {
            get {
                return ResourceManager.GetString("Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 生化檢驗 的當地語系化字串。
        /// </summary>
        public static string Biochemicalexamination {
            get {
                return ResourceManager.GetString("Biochemicalexamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 失明 的當地語系化字串。
        /// </summary>
        public static string Blindness {
            get {
                return ResourceManager.GetString("Blindness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 血壓 的當地語系化字串。
        /// </summary>
        public static string Bloodpressure {
            get {
                return ResourceManager.GetString("Bloodpressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 血型 的當地語系化字串。
        /// </summary>
        public static string Bloodtype {
            get {
                return ResourceManager.GetString("Bloodtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 體重 的當地語系化字串。
        /// </summary>
        public static string Bodyweight {
            get {
                return ResourceManager.GetString("Bodyweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 兄弟 的當地語系化字串。
        /// </summary>
        public static string Brothers {
            get {
                return ResourceManager.GetString("Brothers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取消 的當地語系化字串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 癌症 的當地語系化字串。
        /// </summary>
        public static string Cancer {
            get {
                return ResourceManager.GetString("Cancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 照護 的當地語系化字串。
        /// </summary>
        public static string Care {
            get {
                return ResourceManager.GetString("Care", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關懷群組 的當地語系化字串。
        /// </summary>
        public static string CareGroup {
            get {
                return ResourceManager.GetString("CareGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 白內障 的當地語系化字串。
        /// </summary>
        public static string Cataract {
            get {
                return ResourceManager.GetString("Cataract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檳榔 的當地語系化字串。
        /// </summary>
        public static string Chewingbetelnut {
            get {
                return ResourceManager.GetString("Chewingbetelnut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 慢性併發症 的當地語系化字串。
        /// </summary>
        public static string Chroniccomplications {
            get {
                return ResourceManager.GetString("Chroniccomplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 同學 的當地語系化字串。
        /// </summary>
        public static string Classmate {
            get {
                return ResourceManager.GetString("Classmate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 同事 的當地語系化字串。
        /// </summary>
        public static string Colleague {
            get {
                return ResourceManager.GetString("Colleague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 常用語言 的當地語系化字串。
        /// </summary>
        public static string Commonlanguage {
            get {
                return ResourceManager.GetString("Commonlanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通聯方式 的當地語系化字串。
        /// </summary>
        public static string Contactmethod {
            get {
                return ResourceManager.GetString("Contactmethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 切換 的當地語系化字串。
        /// </summary>
        public static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 慢性阻塞性肺疾病 的當地語系化字串。
        /// </summary>
        public static string COPD {
            get {
                return ResourceManager.GetString("COPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 雞眼 的當地語系化字串。
        /// </summary>
        public static string Corn {
            get {
                return ResourceManager.GetString("Corn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 冠心病 的當地語系化字串。
        /// </summary>
        public static string Coronaryheartdisease {
            get {
                return ResourceManager.GetString("Coronaryheartdisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 夫妻 的當地語系化字串。
        /// </summary>
        public static string Couple {
            get {
                return ResourceManager.GetString("Couple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增個案及帳號 的當地語系化字串。
        /// </summary>
        public static string CreateDMIndex {
            get {
                return ResourceManager.GetString("CreateDMIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已有帳號僅建立個案 的當地語系化字串。
        /// </summary>
        public static string CreateExistAccountDMIndex {
            get {
                return ResourceManager.GetString("CreateExistAccountDMIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立會議室 的當地語系化字串。
        /// </summary>
        public static string CreateMeetingRoom {
            get {
                return ResourceManager.GetString("CreateMeetingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 個案建立 的當地語系化字串。
        /// </summary>
        public static string Createpatientfiles {
            get {
                return ResourceManager.GetString("Createpatientfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 肌酐酸Creatin(mg/dl) 的當地語系化字串。
        /// </summary>
        public static string Creatinine {
            get {
                return ResourceManager.GetString("Creatinine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出生年月日 的當地語系化字串。
        /// </summary>
        public static string DateofBirth {
            get {
                return ResourceManager.GetString("DateofBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確診日期 的當地語系化字串。
        /// </summary>
        public static string Dateofdiagnosis {
            get {
                return ResourceManager.GetString("Dateofdiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要刪除嗎? 的當地語系化字串。
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 詳細 的當地語系化字串。
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 糖尿病 的當地語系化字串。
        /// </summary>
        public static string Diabetesmellitus {
            get {
                return ResourceManager.GetString("Diabetesmellitus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 高滲透壓非酮酸性昏迷(HHNK) 的當地語系化字串。
        /// </summary>
        public static string Diabetichyperosmolarcoma {
            get {
                return ResourceManager.GetString("Diabetichyperosmolarcoma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 糖尿病酮酸血症(DKA) 的當地語系化字串。
        /// </summary>
        public static string Diabeticketoacidosis {
            get {
                return ResourceManager.GetString("Diabeticketoacidosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 洗腎 的當地語系化字串。
        /// </summary>
        public static string Dialysis {
            get {
                return ResourceManager.GetString("Dialysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 消化系統(肝、膽、腸、胃) 的當地語系化字串。
        /// </summary>
        public static string Digestivesystem {
            get {
                return ResourceManager.GetString("Digestivesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身心障礙手冊 的當地語系化字串。
        /// </summary>
        public static string Disabilitymanual {
            get {
                return ResourceManager.GetString("Disabilitymanual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停用 的當地語系化字串。
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 個案 的當地語系化字串。
        /// </summary>
        public static string DM {
            get {
                return ResourceManager.GetString("DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 審核歷史紀錄 的當地語系化字串。
        /// </summary>
        public static string DMAuditHistory {
            get {
                return ResourceManager.GetString("DMAuditHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 個案管理師 的當地語系化字串。
        /// </summary>
        public static string DMDoctor {
            get {
                return ResourceManager.GetString("DMDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 戶籍地址 的當地語系化字串。
        /// </summary>
        public static string Domicileaddress {
            get {
                return ResourceManager.GetString("Domicileaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 血脂異常 的當地語系化字串。
        /// </summary>
        public static string Dyslipidemia {
            get {
                return ResourceManager.GetString("Dyslipidemia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯 的當地語系化字串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 教育程度 的當地語系化字串。
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 兄妹 的當地語系化字串。
        /// </summary>
        public static string ElderBrotherYoungerSister {
            get {
                return ResourceManager.GetString("ElderBrotherYoungerSister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 姊弟 的當地語系化字串。
        /// </summary>
        public static string ElderSisterYoungerBrother {
            get {
                return ResourceManager.GetString("ElderSisterYoungerBrother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 心電圖 的當地語系化字串。
        /// </summary>
        public static string Electrocardiography {
            get {
                return ResourceManager.GetString("Electrocardiography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 緊急聯絡人 的當地語系化字串。
        /// </summary>
        public static string EmergencyContact {
            get {
                return ResourceManager.GetString("EmergencyContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 運動 的當地語系化字串。
        /// </summary>
        public static string Exercise {
            get {
                return ResourceManager.GetString("Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 眼睛檢查 的當地語系化字串。
        /// </summary>
        public static string Eyeexams {
            get {
                return ResourceManager.GetString("Eyeexams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 家族病史 的當地語系化字串。
        /// </summary>
        public static string Familyhistory {
            get {
                return ResourceManager.GetString("Familyhistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 飯前血糖Glucose(AC)(mg/dl) 的當地語系化字串。
        /// </summary>
        public static string Fastingbloodglucose {
            get {
                return ResourceManager.GetString("Fastingbloodglucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 父女 的當地語系化字串。
        /// </summary>
        public static string FatherDaughter {
            get {
                return ResourceManager.GetString("FatherDaughter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 父子 的當地語系化字串。
        /// </summary>
        public static string FatherSon {
            get {
                return ResourceManager.GetString("FatherSon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 女性 的當地語系化字串。
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 足部檢查病變 的當地語系化字串。
        /// </summary>
        public static string Footexamination {
            get {
                return ResourceManager.GetString("Footexamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 忘记密码? 的當地語系化字串。
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 眼底檢查 的當地語系化字串。
        /// </summary>
        public static string Fundusexamination {
            get {
                return ResourceManager.GetString("Fundusexamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 一般項目 的當地語系化字串。
        /// </summary>
        public static string GeneralData {
            get {
                return ResourceManager.GetString("GeneralData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 妊娠糖尿病 的當地語系化字串。
        /// </summary>
        public static string Gestationaldiabetes {
            get {
                return ResourceManager.GetString("Gestationaldiabetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 糖化血色素(HbA1C)(%) 的當地語系化字串。
        /// </summary>
        public static string Glycatedhemoglobin {
            get {
                return ResourceManager.GetString("Glycatedhemoglobin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 祖孫 的當地語系化字串。
        /// </summary>
        public static string GrandAndChild {
            get {
                return ResourceManager.GetString("GrandAndChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 群组 的當地語系化字串。
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 醫事信息 的當地語系化字串。
        /// </summary>
        public static string HealthcareInformation {
            get {
                return ResourceManager.GetString("HealthcareInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 衛生教育 的當地語系化字串。
        /// </summary>
        public static string Healtheducation {
            get {
                return ResourceManager.GetString("Healtheducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 心臟病 的當地語系化字串。
        /// </summary>
        public static string Heartdisease {
            get {
                return ResourceManager.GetString("Heartdisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身高 的當地語系化字串。
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 線上說明 的當地語系化字串。
        /// </summary>
        public static string Helps {
            get {
                return ResourceManager.GetString("Helps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 高血壓 的當地語系化字串。
        /// </summary>
        public static string Hypertension {
            get {
                return ResourceManager.GetString("Hypertension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 姿位性低血壓(Postural hypotension) 的當地語系化字串。
        /// </summary>
        public static string Hypotensionpostural {
            get {
                return ResourceManager.GetString("Hypotensionpostural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編號 的當地語系化字串。
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 識別碼 的當地語系化字串。
        /// </summary>
        public static string ID_1 {
            get {
                return ResourceManager.GetString("ID_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身分證號碼 的當地語系化字串。
        /// </summary>
        public static string IDNo {
            get {
                return ResourceManager.GetString("IDNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 免疫疾病 的當地語系化字串。
        /// </summary>
        public static string Immunediseases {
            get {
                return ResourceManager.GetString("Immunediseases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 個人化標準值 的當地語系化字串。
        /// </summary>
        public static string Individualstandardvalues {
            get {
                return ResourceManager.GetString("Individualstandardvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資訊 的當地語系化字串。
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢驗日期 的當地語系化字串。
        /// </summary>
        public static string Inspectiondate {
            get {
                return ResourceManager.GetString("Inspectiondate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 胰島素 的當地語系化字串。
        /// </summary>
        public static string Insulin {
            get {
                return ResourceManager.GetString("Insulin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 問題追蹤 的當地語系化字串。
        /// </summary>
        public static string IssueTracker {
            get {
                return ResourceManager.GetString("IssueTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 腎臟病變 的當地語系化字串。
        /// </summary>
        public static string Kidneydisease {
            get {
                return ResourceManager.GetString("Kidneydisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 低密度膽固醇(LDL)(mg/dl) 的當地語系化字串。
        /// </summary>
        public static string LDL {
            get {
                return ResourceManager.GetString("LDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 列表 的當地語系化字串。
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清單 的當地語系化字串。
        /// </summary>
        public static string listings {
            get {
                return ResourceManager.GetString("listings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 居住狀況 的當地語系化字串。
        /// </summary>
        public static string Live {
            get {
                return ResourceManager.GetString("Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 現居住址 的當地語系化字串。
        /// </summary>
        public static string Living {
            get {
                return ResourceManager.GetString("Living", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 生活習慣 的當地語系化字串。
        /// </summary>
        public static string livinghabit {
            get {
                return ResourceManager.GetString("livinghabit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 載入中... 的當地語系化字串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 螢幕鎖定 的當地語系化字串。
        /// </summary>
        public static string Lockscreen {
            get {
                return ResourceManager.GetString("Lockscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入 的當地語系化字串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登 入 的當地語系化字串。
        /// </summary>
        public static string Login_Button_Text {
            get {
                return ResourceManager.GetString("Login_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登出 的當地語系化字串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下肢間歇痛(Leg claudication) 的當地語系化字串。
        /// </summary>
        public static string Lowerlimbintermittentclaudication {
            get {
                return ResourceManager.GetString("Lowerlimbintermittentclaudication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下限 的當地語系化字串。
        /// </summary>
        public static string Lowlimit {
            get {
                return ResourceManager.GetString("Lowlimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 黃斑部病變 的當地語系化字串。
        /// </summary>
        public static string Maculardegeneration {
            get {
                return ResourceManager.GetString("Maculardegeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主選單 的當地語系化字串。
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 維護 的當地語系化字串。
        /// </summary>
        public static string Maintain {
            get {
                return ResourceManager.GetString("Maintain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 男性 的當地語系化字串。
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 管理 的當地語系化字串。
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 婚姻狀況 的當地語系化字串。
        /// </summary>
        public static string Maritalstatus {
            get {
                return ResourceManager.GetString("Maritalstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 醫療 的當地語系化字串。
        /// </summary>
        public static string Medical {
            get {
                return ResourceManager.GetString("Medical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處方箋 的當地語系化字串。
        /// </summary>
        public static string Medicalprescription {
            get {
                return ResourceManager.GetString("Medicalprescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 藥物史 的當地語系化字串。
        /// </summary>
        public static string Medicationhistory {
            get {
                return ResourceManager.GetString("Medicationhistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會議室名稱 的當地語系化字串。
        /// </summary>
        public static string MeetingRoomName {
            get {
                return ResourceManager.GetString("MeetingRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 人員 的當地語系化字串。
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 名單 的當地語系化字串。
        /// </summary>
        public static string MemerList {
            get {
                return ResourceManager.GetString("MemerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 手機 的當地語系化字串。
        /// </summary>
        public static string Mobilephone {
            get {
                return ResourceManager.GetString("Mobilephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 母女 的當地語系化字串。
        /// </summary>
        public static string MotherDaughter {
            get {
                return ResourceManager.GetString("MotherDaughter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 母子 的當地語系化字串。
        /// </summary>
        public static string MotherSon {
            get {
                return ResourceManager.GetString("MotherSon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 姓名 的當地語系化字串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 名稱 的當地語系化字串。
        /// </summary>
        public static string Name_1 {
            get {
                return ResourceManager.GetString("Name_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 民族 的當地語系化字串。
        /// </summary>
        public static string Nation {
            get {
                return ResourceManager.GetString("Nation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 神經病變 的當地語系化字串。
        /// </summary>
        public static string Neuropathy {
            get {
                return ResourceManager.GetString("Neuropathy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 提醒通知 的當地語系化字串。
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知設定 的當地語系化字串。
        /// </summary>
        public static string Notificationsettings {
            get {
                return ResourceManager.GetString("Notificationsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 肥胖 的當地語系化字串。
        /// </summary>
        public static string Obesity {
            get {
                return ResourceManager.GetString("Obesity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 職業 的當地語系化字串。
        /// </summary>
        public static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 離線 的當地語系化字串。
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認 的當地語系化字串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 線上 的當地語系化字串。
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 口服藥 的當地語系化字串。
        /// </summary>
        public static string Oralmedication {
            get {
                return ResourceManager.GetString("Oralmedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 其他 的當地語系化字串。
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 其他呼吸系統疾病 的當地語系化字串。
        /// </summary>
        public static string Otherrespiratorydiseases {
            get {
                return ResourceManager.GetString("Otherrespiratorydiseases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總覽 的當地語系化字串。
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 病理資料 的當地語系化字串。
        /// </summary>
        public static string Pathologicaldata {
            get {
                return ResourceManager.GetString("Pathologicaldata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 周邊神經病變(Peripheral neuropathy)1) 的當地語系化字串。
        /// </summary>
        public static string Peripheralneuropathy {
            get {
                return ResourceManager.GetString("Peripheralneuropathy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 個人病史 的當地語系化字串。
        /// </summary>
        public static string PersonalHistory {
            get {
                return ResourceManager.GetString("PersonalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連絡電話 的當地語系化字串。
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 光凝固治療 的當地語系化字串。
        /// </summary>
        public static string Photocoagulationtreatment {
            get {
                return ResourceManager.GetString("Photocoagulationtreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身體檢查 的當地語系化字串。
        /// </summary>
        public static string Physicalexamination {
            get {
                return ResourceManager.GetString("Physicalexamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 圖片 的當地語系化字串。
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 圓餅圖 的當地語系化字串。
        /// </summary>
        public static string PieChart {
            get {
                return ResourceManager.GetString("PieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇... 的當地語系化字串。
        /// </summary>
        public static string PleaseChoose {
            get {
                return ResourceManager.GetString("PleaseChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 飯後血糖(PC)(mg/dl) 的當地語系化字串。
        /// </summary>
        public static string Postprandialbloodglucose {
            get {
                return ResourceManager.GetString("Postprandialbloodglucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預覽 的當地語系化字串。
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主要照顧者 的當地語系化字串。
        /// </summary>
        public static string Primarycaregivers {
            get {
                return ResourceManager.GetString("Primarycaregivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 個人化設定 的當地語系化字串。
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 家屬資料 的當地語系化字串。
        /// </summary>
        public static string ProfileFamilies {
            get {
                return ResourceManager.GetString("ProfileFamilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 增生性視網膜病變 的當地語系化字串。
        /// </summary>
        public static string Proliferativeretinopathy {
            get {
                return ResourceManager.GetString("Proliferativeretinopathy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 增生前視網膜病變 的當地語系化字串。
        /// </summary>
        public static string Proliferativeretinopathybefore {
            get {
                return ResourceManager.GetString("Proliferativeretinopathybefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 脈搏 的當地語系化字串。
        /// </summary>
        public static string Pulse {
            get {
                return ResourceManager.GetString("Pulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 原因 的當地語系化字串。
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 紀錄 的當地語系化字串。
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 拒絕 的當地語系化字串。
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 相關疾病 的當地語系化字串。
        /// </summary>
        public static string Relateddiseases {
            get {
                return ResourceManager.GetString("Relateddiseases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 宗教信仰 的當地語系化字串。
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 管理報表 的當地語系化字串。
        /// </summary>
        public static string Reporting {
            get {
                return ResourceManager.GetString("Reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預約 的當地語系化字串。
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 視網膜檢查 的當地語系化字串。
        /// </summary>
        public static string Retinalexamination {
            get {
                return ResourceManager.GetString("Retinalexamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rh血型 的當地語系化字串。
        /// </summary>
        public static string Rhbloodgroupsystem {
            get {
                return ResourceManager.GetString("Rhbloodgroupsystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲存 的當地語系化字串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋... 的當地語系化字串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 體驗回饋 的當地語系化字串。
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SGPT(u/l) 的當地語系化字串。
        /// </summary>
        public static string Serumalanineaminotransferase {
            get {
                return ResourceManager.GetString("Serumalanineaminotransferase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SGOT(u/l) 的當地語系化字串。
        /// </summary>
        public static string Serumaspartateaminotransferase {
            get {
                return ResourceManager.GetString("Serumaspartateaminotransferase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定 的當地語系化字串。
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立 的當地語系化字串。
        /// </summary>
        public static string SetUp1 {
            get {
                return ResourceManager.GetString("SetUp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 嚴重低血糖 的當地語系化字串。
        /// </summary>
        public static string Severehypoglycemia {
            get {
                return ResourceManager.GetString("Severehypoglycemia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 嚴重低血脂 的當地語系化字串。
        /// </summary>
        public static string Severelowbloodfat {
            get {
                return ResourceManager.GetString("Severelowbloodfat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 性別 的當地語系化字串。
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 姊妹 的當地語系化字串。
        /// </summary>
        public static string Sisters {
            get {
                return ResourceManager.GetString("Sisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 抽煙 的當地語系化字串。
        /// </summary>
        public static string Smoking {
            get {
                return ResourceManager.GetString("Smoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態 的當地語系化字串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 腦中風 的當地語系化字串。
        /// </summary>
        public static string Stroke {
            get {
                return ResourceManager.GetString("Stroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 症狀 的當地語系化字串。
        /// </summary>
        public static string Symptom {
            get {
                return ResourceManager.GetString("Symptom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統設定 的當地語系化字串。
        /// </summary>
        public static string SysSettings {
            get {
                return ResourceManager.GetString("SysSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢驗資料 的當地語系化字串。
        /// </summary>
        public static string Testdata {
            get {
                return ResourceManager.GetString("Testdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 與個案關係 的當地語系化字串。
        /// </summary>
        public static string Therelationshipwiththepatient {
            get {
                return ResourceManager.GetString("Therelationshipwiththepatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 至 的當地語系化字串。
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總膽固醇(T-Chol) 的當地語系化字串。
        /// </summary>
        public static string Totalcholesterol {
            get {
                return ResourceManager.GetString("Totalcholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 趨勢圖 的當地語系化字串。
        /// </summary>
        public static string TrendChart {
            get {
                return ResourceManager.GetString("TrendChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 三酸甘油酯(TG) 的當地語系化字串。
        /// </summary>
        public static string Triglyceride {
            get {
                return ResourceManager.GetString("Triglyceride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 藥物種類 的當地語系化字串。
        /// </summary>
        public static string Typesofdrugs {
            get {
                return ResourceManager.GetString("Typesofdrugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新 的當地語系化字串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上限 的當地語系化字串。
        /// </summary>
        public static string Uplimit {
            get {
                return ResourceManager.GetString("Uplimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BUN(mg/dl) 的當地語系化字串。
        /// </summary>
        public static string Ureanitrogen {
            get {
                return ResourceManager.GetString("Ureanitrogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尿酸(UA)(mg/dl) 的當地語系化字串。
        /// </summary>
        public static string Uricacid {
            get {
                return ResourceManager.GetString("Uricacid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尿蛋白(Protein) 的當地語系化字串。
        /// </summary>
        public static string Urinaryprotein {
            get {
                return ResourceManager.GetString("Urinaryprotein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 泌尿道疾病 的當地語系化字串。
        /// </summary>
        public static string Urinarytractdisease {
            get {
                return ResourceManager.GetString("Urinarytractdisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尿糖(Suger) 的當地語系化字串。
        /// </summary>
        public static string Urine {
            get {
                return ResourceManager.GetString("Urine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Urine檢測日期 的當地語系化字串。
        /// </summary>
        public static string Urinetestdate {
            get {
                return ResourceManager.GetString("Urinetestdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者 的當地語系化字串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 視訊 的當地語系化字串。
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 視訊排程 的當地語系化字串。
        /// </summary>
        public static string VideoSchedule {
            get {
                return ResourceManager.GetString("VideoSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會員 的當地語系化字串。
        /// </summary>
        public static string VIPMember {
            get {
                return ResourceManager.GetString("VIPMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 糖特護照 的當地語系化字串。
        /// </summary>
        public static string WebSiteName {
            get {
                return ResourceManager.GetString("WebSiteName", resourceCulture);
            }
        }
    }
}
