//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetesCarePlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CG_ServiceRecord
    {
        public int PatientID { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int ServiceRecordTypeID { get; set; }
        public int ServiceTypeID { get; set; }
        public string ServiceTypeNote { get; set; }
        public int ServiceResultID { get; set; }
        public string ServiceResultNote { get; set; }
        public string Note { get; set; }
        public string ResponseMessage { get; set; }
        public int CreateUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int LastUserID { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
