//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetesCarePlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMR_DiabetesAlertConfig
    {
        public int CGUnitID { get; set; }
        public int PatientID { get; set; }
        public int ParentUnitID { get; set; }
        public decimal BeforeMealHigh { get; set; }
        public decimal BeforeMealLow { get; set; }
        public decimal AfterMealHigh { get; set; }
        public decimal AfterMealLow { get; set; }
        public decimal OthersHigh { get; set; }
        public decimal OthersLow { get; set; }
        public int MissingCount { get; set; }
        public bool Enable { get; set; }
        public int LastUserID { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
