//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetesCarePlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMRHT_PatientBase
    {
        public int PatientID { get; set; }
        public string PatientName { get; set; }
        public string IdentityNumber { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<decimal> BodyHeight { get; set; }
        public Nullable<decimal> BodyWeight { get; set; }
        public Nullable<int> SexID { get; set; }
        public Nullable<int> RaceTypeID { get; set; }
        public Nullable<int> BloodTypeID { get; set; }
        public Nullable<int> BloodRhTypeID { get; set; }
        public string DisabledID { get; set; }
        public Nullable<int> LanguageTypeID { get; set; }
        public Nullable<int> ReligionTypeID { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> RegisterCountryID { get; set; }
        public Nullable<int> RegisterStateID { get; set; }
        public Nullable<int> RegisterCityID { get; set; }
        public Nullable<int> RegisterDistrictID { get; set; }
        public string RegisterAddress { get; set; }
        public Nullable<int> EducationLevelID { get; set; }
        public int CreateUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int LastUserID { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
