//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetesCarePlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSHT_User
    {
        public int UserID { get; set; }
        public int ParentUnitID { get; set; }
        public string Account { get; set; }
        public byte[] Password { get; set; }
        public string Name { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> AppUserID { get; set; }
        public string IdentityNumber { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> SexID { get; set; }
        public Nullable<int> RaceTypeID { get; set; }
        public Nullable<int> LanguageTypeID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string Address { get; set; }
        public string HomeTelphone { get; set; }
        public string OfficeTelphone { get; set; }
        public string CellPhone { get; set; }
        public string eMail { get; set; }
        public string MobileToken { get; set; }
        public bool Enable { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime VerifyDate { get; set; }
        public int LastUserID { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public Nullable<int> RemoveUserID { get; set; }
        public Nullable<System.DateTime> RemoveDate { get; set; }
    }
}
