//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetesCarePlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSHT_LoginUser
    {
        public int UserID { get; set; }
        public int UnitID { get; set; }
        public string LoginKey { get; set; }
        public string IP { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
