//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetesCarePlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DMCare_PMRPathology
    {
        public int PatientID { get; set; }
        public string ChronicName { get; set; }
        public string ChronicSubName { get; set; }
        public string FamilyHistoryTypeName { get; set; }
        public int PathologyTypeID { get; set; }
        public string PMR_PathologyType { get; set; }
        public string PMR_TagName { get; set; }
        public string ResultValue { get; set; }
    }
}
