//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetesCarePlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DMCare_BasicInformation
    {
        public int PatientID { get; set; }
        public string PatientName { get; set; }
        public Nullable<int> SexID { get; set; }
        public string SexName { get; set; }
        public string IdentityNumber { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string DisabledID { get; set; }
        public Nullable<int> BloodTypeID { get; set; }
        public string BloodTypeName { get; set; }
        public Nullable<int> BloodRhTypeID { get; set; }
        public string BloodRhTypeName { get; set; }
        public Nullable<int> RaceTypeID { get; set; }
        public string RaceTypeName { get; set; }
        public Nullable<int> LanguageTypeID { get; set; }
        public string LanguageTypeName { get; set; }
        public Nullable<int> ReligionTypeID { get; set; }
        public string ReligionTypeName { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public string MaritalStatusName { get; set; }
        public Nullable<int> EducationLevelID { get; set; }
        public string EducationLevelName { get; set; }
        public string CaseStatus { get; set; }
        public int ChronicSubTypeID { get; set; }
        public string ChronicSubName { get; set; }
        public Nullable<int> RegisterCountryID { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> RegisterStateID { get; set; }
        public string StateName { get; set; }
        public Nullable<int> RegisterCityID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> RegisterDistrictID { get; set; }
        public string DistrictName { get; set; }
        public string RegisterAddress { get; set; }
        public Nullable<int> NowCountryID { get; set; }
        public string NowCountryName { get; set; }
        public Nullable<int> NowStateID { get; set; }
        public string NowStateName { get; set; }
        public Nullable<int> NowCityID { get; set; }
        public string NowCityName { get; set; }
        public Nullable<int> NowDistrictID { get; set; }
        public string NowDistrictName { get; set; }
        public string NowAddress { get; set; }
        public string CellPhone { get; set; }
        public string HomeTelphone { get; set; }
        public string OfficeTelphone { get; set; }
        public string eMail { get; set; }
        public Nullable<int> LivingStatus { get; set; }
        public string LivingStatusName { get; set; }
        public Nullable<int> ProfessionID { get; set; }
        public string ProfessionTypeName { get; set; }
        public Nullable<int> SmokeTypeID { get; set; }
        public string SmokeTypeName { get; set; }
        public Nullable<int> DrinkTypeID { get; set; }
        public string DrinkTypeName { get; set; }
        public Nullable<int> ArecaTypeID { get; set; }
        public string ArecaTypeName { get; set; }
    }
}
